### Get All Journal Entries
GET {{host}}/journal

### Create Journal Entry
POST {{host}}/journal
Content-Type: application/json

{
  "title": "My First Entry",
  "content": "Today I started building my Spring Boot Journal App.",
  "date": "2026-02-15T10:30:00"
}

### Get Journal Entry By ID
GET {{host}}/journal/699183d3cd50a5e4d955f48b

### Update Journal Entry
PUT {{host}}/journal/699183d3cd50a5e4d955f48b
Content-Type: application/json

{
  "title": "Updated Entry",
  "content": "I improved my API design today.",
  "date": "2026-02-15T18:00:00"
}


### Delete Journal Entry
DELETE {{host}}/journal/699183d3cd50a5e4d955f48b

