### Get All Journal Entries
GET {{host}}/journal

### Create Journal Entry
POST {{host}}/journal/Manoj
Content-Type: application/json

{
  "title": "My First Entry",
  "content": "Today I started using my journal API.",
  "date": "2026-02-15T17:00:00"
}

### Get Journal Entry By ID
GET {{host}}/journal?userName=Manoj

### Update Journal Entry
PUT {{host}}/journal/alice/1
Content-Type: application/json

{
  "title": "Updated Entry",
  "content": "I improved my API design today.",
  "date": "2026-02-15T18:00:00"
}

### Delete Journal Entry
DELETE {{host}}/journal/alice/1

